apiVersion: v1
kind: Secret
metadata:
  name: csi-s3-secret
  namespace: csi-s3
stringData:
  accessKeyID: DO00HAW8CZ3EWPQLC42V
  secretAccessKey: BoP8tgm7HCIvXVtSs7KThjIl3su7+wcHoyohZ0JAgTg
  endpoint: https://fra1.digitaloceanspaces.com
  